# Generated by Django 5.0.4 on 2024-05-01 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('repeticiones', models.CharField(max_length=100)),
                ('parte_trabajada', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ejercicios', models.ManyToManyField(related_name='planes', to='sis.ejercicio')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
